apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  config.json: |
    {
      "port": {{ .Values.service.port }},
      "interface": "{{ .Values.service.interface }}",
      "github_user": "{{ .Values.GITHUB_USER }}",
      "github_pat": "{{ .Values.GITHUB_PAT }}"
    }
